[package]
name = "php-server"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
php-cli = { path = "../php-cli", optional = true }
php-runtime.workspace = true
mimalloc.workspace = true
tokio = { version = "1", features = ["full"], optional = true }
axum = { version = "0.7", optional = true }
tower = { version = "0.4", optional = true }
hyper = { version = "1", optional = true }

[features]
default = ["cli-server"]
cli-server = ["php-cli"]
axum-server = ["tokio", "axum", "tower", "hyper"]
