#!/bin/bash
# verdict81.sh — S-81.0 step 7 (KG-82-1: every derived table comes from a
# COMMITTED raw->table script, never hand transcription). Reads the 81.*
# campaign raws (wp78-harness/measure-out), emits the per-(arm,fixture)
# steady-mean table + IN-CAMPAIGN spread (A-SK18/KG-82-2), and judges the
# design79 §10 predictions by machine:
#   P1  hello a_calls(HIT) < 4000 (punctual) AND < 8048 (KS-AH-80-4 v2,
#       >=90% drop vs the 80.476 baseline — VOID-gate)
#   P2  a1_calls == 0 steady (no lower_prelude on HIT)
#   P3  a3 == 0 steady (include units still HIT)
#   P4  bare a_calls(HIT) <= 200 (the measured ex-post floor; KB-82-3:
#       >200 = the ex-ante floor was wrong, re-derive BY NAME)
#   P5  resid(hello) within 44.1+-15 calls / 43463+-5000 B (MEAN, A-BG23)
#   P6  b invariant +-5% (hello 730/95627; include_heavy 27982/1867510)
#   P7  retain_len = 1/1/3/6 (bare/hello/include_gate/include_heavy:
#       main park + include park-events, design79 §4)
#   P8  depth_max<=1, inflight_max<=1, a3_trip==0 (re-checked from raws)
export PATH=/usr/bin:/bin:/usr/sbin:/opt/homebrew/bin:$PATH
set -u
HERE="$(cd "$(dirname "$0")" && pwd)"
MOUT="$HERE/../wp78-harness/measure-out"
AN="$HERE/../wp80-harness/analyze80.pl"
FAILS=0
p() { echo "$@"; }
fail() { echo "FAIL: $*"; FAILS=$((FAILS+1)); }

field() { # <line> <key> -> value or empty
  printf '%s\n' "$1" | tr ' ' '\n' | awk -F= -v k="$2" '$1==k{print $2}'
}

p "# verdict81 — lever-arm steady means (gross churn, >= upper bound)"
p "# generated by wp81-harness/verdict81.sh (KG-82-1) — do not hand-edit"
p ""
p "| arm | fixture | a_calls r1/r2/r3 | spread% | a1 | a3 | b_calls | resid_c | retain |"
p "|---|---|---|---|---|---|---|---|---|"

declare -a HELLO_A BARE_A
for arm in census censuscli; do
  for fx in hello include_gate include_heavy bare; do
    L1=$(perl "$AN" "$MOUT/$arm.81.$fx.r1.census" 2>/dev/null) || { fail "missing raw $arm.81.$fx.r1"; continue; }
    L2=$(perl "$AN" "$MOUT/$arm.81.$fx.r2.census" 2>/dev/null) || { fail "missing raw $arm.81.$fx.r2"; continue; }
    L3=$(perl "$AN" "$MOUT/$arm.81.$fx.r3.census" 2>/dev/null) || { fail "missing raw $arm.81.$fx.r3"; continue; }
    if [ "$arm" = census ]; then K=a_calls; else K=total_calls; fi
    A1=$(field "$L1" $K); A2=$(field "$L2" $K); A3v=$(field "$L3" $K)
    SPREAD=$(awk -v a="$A1" -v b="$A2" -v c="$A3v" 'BEGIN{mx=a;mn=a; if(b>mx)mx=b; if(b<mn)mn=b; if(c>mx)mx=c; if(c<mn)mn=c; if(mn==0){print "inf"} else printf "%.2f", (mx-mn)*100/mn}')
    A1C=$(field "$L1" a1_calls); A3C=$(field "$L1" a3_calls)
    BC=$(field "$L1" b_calls); RC=$(field "$L1" resid_calls); RET=$(field "$L1" retain_len)
    p "| $arm | $fx | $A1/$A2/$A3v | $SPREAD | ${A1C:-na} | ${A3C:-na} | ${BC:-na} | ${RC:-na} | ${RET:-na} |"
    if [ "$arm" = census ]; then
      [ "$fx" = hello ] && HELLO_A=("$A1" "$L1" "$L2" "$L3")
      [ "$fx" = bare ] && BARE_A=("$A1" "$L1")
    fi
  done
done
p ""

# --- predictions (census arm judges; cli arm is the declared-asymmetry twin) --
L="${HELLO_A[1]:-}"
[ -z "$L" ] && { fail "no hello census line"; echo "== VERDICT81 FAIL($FAILS) =="; exit 1; }
AC=$(field "$L" a_calls); A1C=$(field "$L" a1_calls); A3C=$(field "$L" a3_calls)
RC=$(field "$L" resid_calls); RB=$(field "$L" resid_bytes); BC=$(field "$L" b_calls); BB=$(field "$L" b_bytes)
RET=$(field "$L" retain_len)
awk -v v="$AC" 'BEGIN{exit !(v<4000)}' && p "P1a PASS: hello a_calls=$AC < 4000" || fail "P1a hello a_calls=$AC >= 4000"
awk -v v="$AC" 'BEGIN{exit !(v<8048)}' && p "P1b PASS: >=90% drop (a_calls=$AC < 8048, KS-AH-80-4 v2)" || fail "P1b VOID-gate: a_calls=$AC >= 8048"
awk -v v="$A1C" 'BEGIN{exit !(v==0)}' && p "P2  PASS: a1_calls==0 steady" || fail "P2 a1_calls=$A1C != 0"
awk -v v="$A3C" 'BEGIN{exit !(v==0)}' && p "P3  PASS: a3_calls==0 steady" || fail "P3 a3_calls=$A3C != 0"
BAC="${BARE_A[0]:-999999}"
awk -v v="$BAC" 'BEGIN{exit !(v<=200)}' && p "P4  PASS: bare a_calls(HIT)=$BAC <= 200 (measured ex-post floor)" || fail "P4 KB-82-3: bare a_calls=$BAC > 200 — floor bucato, rideriva PER NOME"
awk -v v="$RC" 'BEGIN{exit !(v>=29.1 && v<=59.1)}' && p "P5a PASS: resid_calls=$RC in 44.1+-15" || fail "P5a resid_calls=$RC outside 44.1+-15"
awk -v v="$RB" 'BEGIN{exit !(v>=38463 && v<=48463)}' && p "P5b PASS: resid_bytes=$RB in 43463+-5000" || fail "P5b resid_bytes=$RB outside 43463+-5000"
awk -v v="$BC" 'BEGIN{exit !(v>=693.5 && v<=766.5)}' && p "P6a PASS: hello b_calls=$BC within +-5% of 730" || fail "P6a b_calls=$BC outside 730+-5%"
LH=$(perl "$AN" "$MOUT/census.81.include_heavy.r1.census" 2>/dev/null)
BH=$(field "$LH" b_calls)
awk -v v="$BH" 'BEGIN{exit !(v>=26582.9 && v<=29381.1)}' && p "P6b PASS: include_heavy b_calls=$BH within +-5% of 27982" || fail "P6b include_heavy b_calls=$BH outside 27982+-5%"
awk -v v="$RET" 'BEGIN{exit !(v==1)}' && p "P7a PASS: hello retain_len==1 (main park)" || fail "P7a hello retain_len=$RET != 1"
for spec in "bare:1" "include_gate:3" "include_heavy:6"; do
  fx="${spec%%:*}"; want="${spec##*:}"
  LX=$(perl "$AN" "$MOUT/census.81.$fx.r1.census" 2>/dev/null); RX=$(field "$LX" retain_len)
  awk -v v="$RX" -v w="$want" 'BEGIN{exit !(v==w)}' && p "P7  PASS: $fx retain_len==$want" || fail "P7 $fx retain_len=$RX != $want"
done
for fx in hello include_gate include_heavy bare; do
  LX=$(perl "$AN" "$MOUT/census.81.$fx.r1.census" 2>/dev/null)
  DM=$(printf '%s\n' "$LX" | tr ' ' '\n' | awk -F= '$1=="depth_max_max"{print $2}')
  IM=$(printf '%s\n' "$LX" | tr ' ' '\n' | awk -F= '$1=="inflight_max_max"{print $2}')
  TP=$(printf '%s\n' "$LX" | tr ' ' '\n' | awk -F= '$1=="a3_trip_max"{print $2}')
  if [ "${DM:-9}" -le 1 ] && [ "${IM:-9}" -le 1 ] && [ "${TP:-9}" -eq 0 ]; then
    p "P8  PASS: $fx depth<=1 inflight<=1 trip==0"
  else
    fail "P8 $fx tripwires: depth=$DM inflight=$IM trip=$TP"
  fi
done

if [ "$FAILS" = 0 ]; then
  echo "== VERDICT81 PASS (all §10 predictions) =="
  exit 0
else
  echo "== VERDICT81 FAIL($FAILS) =="
  exit 1
fi
